### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by nullified33** [TechReborn/Energy#16]
[02/01/2022 17:55:01 PM] [Render thread/INFO] Failed to find module info for **USERSDIR**\temp\natives-055c324afd1444499818e4ac1bdf94a4\SAPIWrapper_x64.dll
[02/01/2022 17:55:01 PM] ---- Minecraft Crash Report ----
[02/01/2022 17:55:01 PM] // Don't be sad, have a hug! <3
[02/01/2022 17:55:01 PM] 
[02/01/2022 17:55:01 PM] Time: 1/2/22, 5:55 PM
[02/01/2022 17:55:01 PM] Description: Initializing game
[02/01/2022 17:55:01 PM] 
[02/01/2022 17:55:01 PM] java.lang.IllegalStateException: Config not yet available
[02/01/2022 17:55:01 PM] 	at me.jellysquid.mods.sodium.client.SodiumClientMod.options(SodiumClientMod.java:34)
[02/01/2022 17:55:01 PM] 	at net.minecraft.class_310.handler$eie000$postInit(class_310.java:17976)
[02/01/2022 17:55:01 PM] 	at net.minecraft.class_310.<init>(class_310.java:637)
[02/01/2022 17:55:01 PM] 	at net.minecraft.client.main.Main.main(Main.java:199)
[02/01/2022 17:55:01 PM] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[02/01/2022 17:55:01 PM] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[02/01/2022 17:55:01 PM] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[02/01/2022 17:55:01 PM] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[02/01/2022 17:55:01 PM] 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
[02/01/2022 17:55:01 PM] 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
[02/01/2022 17:55:01 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[02/01/2022 17:55:01 PM] 
[02/01/2022 17:55:01 PM] 
[02/01/2022 17:55:01 PM] A detailed walkthrough of the error, its code path and all known details is as follows:
[02/01/2022 17:55:01 PM] ---------------------------------------------------------------------------------------
[02/01/2022 17:55:01 PM] 
[02/01/2022 17:55:01 PM] -- Head --
[02/01/2022 17:55:01 PM] Thread: Render thread
[02/01/2022 17:55:01 PM] Stacktrace:
[02/01/2022 17:55:01 PM] 	at me.jellysquid.mods.sodium.client.SodiumClientMod.options(SodiumClientMod.java:34)
[02/01/2022 17:55:01 PM] 	at net.minecraft.class_310.handler$eie000$postInit(class_310.java:17976)
[02/01/2022 17:55:01 PM] 	at net.minecraft.class_310.<init>(class_310.java:637)
[02/01/2022 17:55:01 PM] 
[02/01/2022 17:55:01 PM] -- Initialization --
[02/01/2022 17:55:01 PM] Details:
[02/01/2022 17:55:01 PM] 	Modules: 
[02/01/2022 17:55:01 PM] 		ADVAPI32.dll:Advanced Windows 32 Base API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
[02/01/2022 17:55:01 PM] 		COMCTL32.dll:User Experience Controls Library:6.10 (WinBuild.160101.0800):Microsoft Corporation
[02/01/2022 17:55:01 PM] 		CRYPT32.dll:Crypto API32:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
[02/01/2022 17:55:01 PM] 		CRYPTBASE.dll:Base cryptographic API DLL:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
[02/01/2022 17:55:01 PM] 		CRYPTSP.dll:Cryptographic Service Provider API:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
[02/01/2022 17:55:01 PM] 		ColorAdapterClient.dll:Microsoft Color Adapter Client:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
[02/01/2022 17:55:01 PM] 		CoreMessaging.dll:Microsoft CoreMessaging Dll:10.0.19041.746:Microsoft Corporation
[02/01/2022 17:55:01 PM] 		CoreUIComponents.dll:Microsoft Core UI Components Dll:10.0.19041.546:Microsoft Corporation
[02/01/2022 17:55:01 PM] 		DBGHELP.DLL:Windows Image Helper:10.0.19041.867 (WinBuild.160101.0800):Microsoft Corporation
[02/01/2022 17:55:01 PM] 		DEVOBJ.dll:Device Information Set DLL:10.0.19041.1151 (WinBuild.160101.0800):Microsoft Corporation
[02/01/2022 17:55:01 PM] 		DNSAPI.dll:DNS Client API DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
[02/01/2022 17:55:01 PM] 		GDI32.dll:GDI Client DLL:10.0.19041.1202 (WinBuild.160101.0800):Microsoft Corporation
[02/01/2022 17:55:01 PM] 		GLU32.dll:OpenGL Utility Library DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
[02/01/2022 17:55:01 PM] 		HID.DLL:Hid User Library:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
[02/01/2022 17:55:01 PM] 		IMM32.DLL:Multi-User Windows IMM32 API Client DLL:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
[02/01/2022 17:55:01 PM] 		IPHLPAPI.DLL:IP Helper API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
[02/01/2022 17:55:01 PM] 		KERNEL32.DLL:Windows NT BASE API Client DLL:10.0.19041.1348 (WinBuild.160101.0800):Microsoft Corporation
[02/01/2022 17:55:01 PM] 		KERNELBASE.dll:Windows NT BASE API Client DLL:10.0.19041.1348 (WinBuild.160101.0800):Microsoft Corporation
[02/01/2022 17:55:01 PM] 		MMDevApi.dll:MMDevice API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
[02/01/2022 17:55:01 PM] 		MSACM32.dll:Microsoft ACM Audio Filter:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
[02/01/2022 17:55:01 PM] 		MSASN1.dll:ASN.1 Runtime APIs:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
[02/01/2022 17:55:01 PM] 		MSCTF.dll:MSCTF Server DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
[02/01/2022 17:55:01 PM] 		MpOav.dll:IOfficeAntiVirus Module:4.18.2111.5 (WinBuild.160101.0800):Microsoft Corporation
[02/01/2022 17:55:01 PM] 		NLAapi.dll:Network Location Awareness 2:10.0.19041.1151 (WinBuild.160101.0800):Microsoft Corporation
[02/01/2022 17:55:01 PM] 		NSI.dll:NSI User-mode interface DLL:10.0.19041.610 (WinBuild.160101.0800):Microsoft Corporation
[02/01/2022 17:55:01 PM] 		NTASN1.dll:Microsoft ASN.1 API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
[02/01/2022 17:55:01 PM] 		Ole32.dll:Microsoft OLE for Windows:10.0.19041.1320 (WinBuild.160101.0800):Microsoft Corporation
[02/01/2022 17:55:01 PM] 		OleAut32.dll:OLEAUT32.DLL:10.0.19041.985 (WinBuild.160101.0800):Microsoft Corporation
[02/01/2022 17:55:01 PM] 		Oleacc.dll:Active Accessibility Core Component:7.2.19041.746 (WinBuild.160101.0800):Microsoft Corporation
[02/01/2022 17:55:01 PM] 		OpenAL.dll
[02/01/2022 17:55:01 PM] 		PROPSYS.dll:Microsoft Property System:7.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
[02/01/2022 17:55:01 PM] 		PSAPI.DLL:Process Status Helper:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
[02/01/2022 17:55:01 PM] 		Pdh.dll:Windows Performance Data Helper DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
[02/01/2022 17:55:01 PM] 		RPCRT4.dll:Remote Procedure Call Runtime:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
[02/01/2022 17:55:01 PM] 		SAPIWrapper_x64.dll
[02/01/2022 17:55:01 PM] 		SETUPAPI.DLL:Windows Setup API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
[02/01/2022 17:55:01 PM] 		SHCORE.dll:SHCORE:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
[02/01/2022 17:55:01 PM] 		SHELL32.dll:Windows Shell Common Dll:10.0.19041.964 (WinBuild.160101.0800):Microsoft Corporation
[02/01/2022 17:55:01 PM] 		WS2_32.dll:Windows Socket 2.0 32-Bit DLL:10.0.19041.1081 (WinBuild.160101.0800):Microsoft Corporation
[02/01/2022 17:55:01 PM] 		advanced_runtime_resource_pack: Runtime Resource Pack 0.5.4
[02/01/2022 17:55:01 PM] 		team_reborn_energy: Energy 2.0.0-beta1
[02/01/2022 17:55:02 PM] Oh no. Minecraft crashed. Please check the logs for any errors and provide these logs when asking for support.
[02/01/2022 17:55:02 PM] Checking for updated files!

**Comment by xanthian** [comment]
???
context please.

**Comment by Jamalam360** [comment]
What makes you think this is a TechReborn/Energy issue? Does the issue stop happening if you remove the mod?

**Comment by xanthian** [comment]
Looks like sodium to me too

**Comment by nullified33** [comment]
Ok
